### ISSUE TITLE
Cannot read property 'clear' of undefined

### ISSUE THREAD

**Issue by phachon** [sirensolutions/kaae#69]
I have a problem in using kaae.
I can't find any other way to solve that:
Here's my error message

```
Unhandled rejection TypeError: Cannot read property 'clear' of undefined
    at /usr/local/elk/kibana-4.6.1/installedPlugins/kaae/server/lib/scheduler.js:50:39
    at arrayEach (/usr/local/elk/kibana-4.6.1/installedPlugins/kaae/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/elk/kibana-4.6.1/installedPlugins/kaae/node_modules/lodash/index.js:3345:13)
    at /usr/local/elk/kibana-4.6.1/installedPlugins/kaae/server/lib/scheduler.js:48:11
    at tryCatcher (/usr/local/elk/kibana-4.6.1/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/elk/kibana-4.6.1/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/elk/kibana-4.6.1/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/elk/kibana-4.6.1/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/elk/kibana-4.6.1/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/elk/kibana-4.6.1/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/elk/kibana-4.6.1/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```
Here's my kaae watcher config:

```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_9emulp85f",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 5 minutes"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "logstash-nginx"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 10"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "phachon@163.com",
          "subject": "KaaE Alarm test",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    }
  }
}
```
How should I modify the configuration?
Thanks...

**Comment by lmangani** [comment]
KAAE is trying to remove an orphaned (deleted) watcher but it seems to lack the schedule. Do you have output preceding this error?

**Comment by lmangani** [comment]
@phachon I pushed a patch to avoid the error when a deleted watcher is missing the schedule, but in order to correctly understand the scenario we need a step-by-step sequence in terms of what triggers it, including the watcher configuration and any log output. Thanks in advance!

**Comment by phachon** [comment]
ok, Thank you for your answer.
It is very strange that I did not meet yesterday's error.
But I want to send my alarm message to my mail is still not successful.

kibana log message:
```
log   [11:06:25.807] [info][status][KaaE] Scheduled Watch: new_watcher_4khg6v0oz every every 5 minutes
log   [11:10:00.004] [info][status][KaaE] Executing watch: new_watcher_4khg6v0oz
log   [11:10:00.013] [info][status][KaaE] Action Report requires Email Settings! Reports Disabled.
log   [11:10:00.015] [info][status][KaaE] Processing action: email_admin
log   [11:10:00.016] [info][status][KaaE] Action Throtthled: email_admin

```
kaae.json configuration:

```
"settings" : {
        "email" : {
           "user":      "phachon@163.com",
           "password":  "*****",
           "host":      "smtp.163.com",
           "ssl":       true,
           "active":    false
        },
        ....
```
watcher actions configuration:

```
"actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "***@***.com",
          "from": "phachon@163.com",
          "subject": "KaaE Alarm TEST",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    }
```

Thanks...

**Comment by lmangani** [comment]
Hi @phachon the logs indicate the action was throttled, thus not sent:
```
log   [11:10:00.016] [info][status][KaaE] Action Throtthled: email_admin
```

Please set the throttle time compatibly with the frequency (or even inferior to the schedule rotation) to confirm if emails are being sent. Everything else looks fine.

**Comment by phachon** [comment]
Hi @lmangani  set the throttle time ?

watcher actions configuration:

```
"email_admin": {
        "throttle_period": "15m",    
 }
```
I am tring to update 'throttle_period' , still not successful.
```
log   [18:11:00.002] [info][status][KaaE] Executing watch: new_watcher_4khg6v0oz
log   [18:11:00.007] [info][status][KaaE] Action Report requires Email Settings! Reports Disabled.
log   [18:11:00.007] [info][status][KaaE] Processing action: email_admin
log   [18:11:00.008] [info][status][KaaE] Action Throtthled: email_admin
log   [18:12:00.004] [info][status][KaaE] Executing watch: new_watcher_4khg6v0oz
log   [18:12:00.010] [info][status][KaaE] Action Report requires Email Settings! Reports Disabled.
log   [18:12:00.010] [info][status][KaaE] Processing action: email_admin
log   [18:12:00.011] [info][status][KaaE][email] Subject: KaaE Alarm TEST, Body: Found 473785 Events
log   [18:12:00.012] [info][status][Kaae][email] Delivery Disabled!
log   [18:12:00.012] [info][status][KaaE] Storing Alarm to ES with type:email_admin
log   [18:13:00.002] [info][status][KaaE] Executing watch: new_watcher_4khg6v0oz

```
what should I do?

**Comment by lmangani** [comment]
@phachon the watcher is working fine :) You just have to enable actual delivery in ```/etc/kaae.json``` and emails will be delivered to SMTP

**Comment by phachon** [comment]
@lmangani , I finally found the cause of the problem by looking at the source code.

default kaae config.json

```
"settings" : {
    "email" : {
       "user":  "username", 
       "password":  "password", 
       "host":  "smtp.server.com", 
       "ssl":   true,
       "active":    false
    },
``` 
because "active": false .....

server/lib/actions.js in 186 line 
```
if (!email_server || !config.settings.email.active) {
                server.log(['status', 'info', 'Kaae', 'email'], 'Delivery Disabled!');
            }
            else {
                server.log(['status', 'info', 'Kaae', 'email'], 'Delivering to Mail Server');
                email_server.send({
                    text: body,
                    from: action.email.from,
                    to: action.email.to,
                    subject: subject
                }, function (err, message) {
                    server.log(['status', 'info', 'Kaae', 'email'], err || message);
                });
            }
```
so, my server log still print 'Delivery Disabled!'.

I changed 'active': true , finally succeeded.

Anyway,thank you very much.

**Comment by lmangani** [comment]
Hi @phachon this is explained in the wiki and valid for all configurable actions. Glad you got it figured!
